name: "Policy Push"
description: "Push policy image to registry"
author: "Aserto Inc."
branding:
  icon: skip-forward
  color: blue
inputs:
  tags:
    description: "one or more image tags to be pushed"
    required: true
  verbosity:
    description: "verbosity level [info|error|debug|trace]"
    required: true
    default: error
runs:
  using: docker
  image: 'docker://ghcr.io/opcr-io/policy:0.1'
  entrypoint: /app/push.sh
